# -*- coding: utf-8 -*-

import numpy as np
import openmdao.api as om
import pandas as pd
import logging
import traceback
import os

import hydesign.HiFiEMS.EMS_assembly as EMS
from hydesign.ems.ems import expand_to_lifetime
from hydesign.HiFiEMS.EMS_assembly import EMS
from hydesign.openmdao_wrapper import ComponentWrapper

# Disable logging to suppress debug output
logging.getLogger('matplotlib').setLevel(logging.WARNING)
logging.getLogger().setLevel(logging.WARNING)

# Create logger for this module
logger = logging.getLogger(__name__)


class ems:
    """Energy management optimization model
    The energy management system optimization model consists in maximizing the revenue generated by the plant over a period of time,
    including a possible penalty for not meeting the requirement of energy generation during peak hours over the period. It also assigns
    a cost for rapid fluctuations of the battery in order to slow down its degradation.
    The EMS type can be either a CPLEX optimization or a rule-based ems (Faster but not as optimal).

    Parameters
    ----------
    wind_t : WPP power time series [MW]
    solar_t : PVP power time series [MW]
    price_t : Electricity price time series
    b_P : Battery power capacity [MW]
    b_E : Battery energy storage capacity [MW]
    G_MW : Grid capacity [MW]
    battery_depth_of_discharge : battery depth of discharge
    peak_hr_quantile : Quantile of price time series to define peak price hours (above this quantile)
    cost_of_battery_P_fluct_in_peak_price_ratio : cost of battery power fluctuations computed as a peak price ratio
    n_full_power_hours_expected_per_day_at_peak_price : Penalty occurs if number of full power hours expected per day at peak price are not reached

    Returns
    -------
    wind_t_ext : WPP power time series
    solar_t_ext : PVP power time series
    price_t_ext : Electricity price time series
    hpp_t : HPP power time series
    hpp_curt_t : HPP curtailed power time series
    b_t : Battery charge/discharge power time series
    b_E_SOC_t : Battery energy SOC time series
    penalty_t : Penalty for not reaching expected energy productin at peak hours

    """

    def __init__(
        self,
        parameter_dict,
        simulation_dict,
        N_time,
        life_y=25,
        intervals_per_hour=None,
        SMOpt="DO",
        BMOpt=None,
        RDOpt=None,
    ):

        self.parameter_dict = parameter_dict
        self.simulation_dict = simulation_dict
        
        # Compute intervals_per_hour from dispatch_interval if not explicitly provided
        if intervals_per_hour is None:
            dispatch_interval = parameter_dict.get("dispatch_interval", 1 / 4)
            intervals_per_hour = int(1 / dispatch_interval)
        
        self.intervals_per_hour = intervals_per_hour
        self.life_y = life_y
        self.life_h = 365 * 24 * life_y
        self.life_intervals = self.life_h * intervals_per_hour
        self.yearly_intervals = intervals_per_hour * 365 * 24
        self.N_time = N_time
        self.SMOpt = SMOpt
        self.BMOpt = BMOpt
        self.RDOpt = RDOpt

    def compute(self, **inputs):
        outputs = {}
        parameter_dict = self.parameter_dict
        parameter_dict.update(
            {
                # hpp parameters
                "hpp_grid_connection": float(inputs["G_MW"][0]),  # in MW
                # hpp wind parameters
                "wind_capacity": float(inputs["wind_MW"][0]),  # in MW
                # hpp solar parameters
                "solar_capacity": float(inputs["solar_MW"][0]),  # in MW
                # hpp battery parameters
                "battery_energy_capacity": float(inputs["b_E"][0]),  # in MWh
                "battery_power_capacity": float(inputs["b_P"][0]),  # in MW
                "battery_minimum_SoC": 1
                - float(inputs["battery_depth_of_discharge"][0]),
            }
        )

        simulation_dict = self.simulation_dict
        out_keys = [
            "P_HPP_SM_t_opt",
            "SM_price_cleared",
            "BM_dw_price_cleared",
            "BM_up_price_cleared",
            "P_HPP_RT_ts",
            "P_HPP_RT_refs",
            "P_HPP_UP_bid_ts",
            "P_HPP_DW_bid_ts",
            "s_UP_t",
            "s_DW_t",
            "residual_imbalance",
            "RES_RT_cur_ts",
            "P_dis_RT_ts",
            "P_cha_RT_ts",
            "SoC_ts",
        ]

        config = {
            "SMOpt": self.SMOpt,
            "BMOpt": self.BMOpt,
            "RDOpt": self.RDOpt,
        }
        EMS_model = EMS(config=config)

        # Check if battery capacity is zero and set to minimal value to allow EMS to compute
        # wind and solar optimization. The minimal battery won't actually be used but allows EMS to run.
        battery_capacity = float(inputs["b_P"][0])
        battery_energy = float(inputs["b_E"][0])
        wind_capacity = float(inputs["wind_MW"][0])
        solar_capacity = float(inputs["solar_MW"][0])
        
        # If battery is zero, set to minimal value to allow EMS optimization of wind/solar
        if battery_capacity <= 0:
            battery_capacity = 1e-6  # Minimal value in MW
            parameter_dict["battery_power_capacity"] = battery_capacity
            logger.info(
                f"Battery power capacity was zero. Set to {battery_capacity} MW for EMS computation. "
                f"Wind: {wind_capacity} MW, Solar: {solar_capacity} MW"
            )
        if battery_energy <= 0:
            battery_energy = 1e-6  # Minimal value in MWh
            parameter_dict["battery_energy_capacity"] = battery_energy
            logger.info(
                f"Battery energy capacity was zero. Set to {battery_energy} MWh for EMS computation. "
                f"Wind: {wind_capacity} MW, Solar: {solar_capacity} MW"
            )
        
        # If wind capacity is zero (pure solar), set to minimal value to avoid division by zero in EMS
        if wind_capacity <= 0:
            wind_capacity = 1e-6  # Minimal value in MW
            parameter_dict["wind_capacity"] = wind_capacity
            logger.info(
                f"Wind capacity was zero (pure solar configuration). Set to {wind_capacity} MW for EMS computation. "
                f"Solar: {solar_capacity} MW"
            )
        
        # If solar capacity is zero (pure wind), set to minimal value to avoid division by zero in EMS
        if solar_capacity <= 0:
            solar_capacity = 1e-6  # Minimal value in MW
            parameter_dict["solar_capacity"] = solar_capacity
            logger.info(
                f"Solar capacity was zero (pure wind configuration). Set to {solar_capacity} MW for EMS computation. "
                f"Wind: {wind_capacity} MW"
            )

        try:
            (
                P_HPP_SM_t_opt,
                SM_price_cleared,
                BM_dw_price_cleared,
                BM_up_price_cleared,
                P_HPP_RT_ts,
                P_HPP_RT_refs,
                P_HPP_UP_bid_ts,
                P_HPP_DW_bid_ts,
                s_UP_t,
                s_DW_t,
                residual_imbalance,
                RES_RT_cur_ts,
                P_dis_RT_ts,
                P_cha_RT_ts,
                E_SOC_ts,
            ) = EMS_model.run(
                parameter_dict=parameter_dict,
                simulation_dict=simulation_dict,
            )
            # wind_t, solar_t, and P_curtailment_ts are not returned by EMS.run(), initialize as zeros
            wind_t = np.zeros(len(P_HPP_RT_ts))
            solar_t = np.zeros(len(P_HPP_RT_ts))
            P_curtailment_ts = np.zeros(len(P_HPP_RT_ts))
        except (IndexError, ValueError, TypeError) as e:
            # Log error details for diagnosis
            error_msg = f"EMS.run() failed: {type(e).__name__}: {str(e)}\n"
            error_msg += f"  battery_power_capacity: {parameter_dict.get('battery_power_capacity', 'N/A')}\n"
            error_msg += f"  battery_energy_capacity: {parameter_dict.get('battery_energy_capacity', 'N/A')}\n"
            error_msg += f"  wind_capacity: {parameter_dict.get('wind_capacity', 'N/A')}\n"
            error_msg += f"  solar_capacity: {parameter_dict.get('solar_capacity', 'N/A')}\n"
            error_msg += f"Traceback:\n{traceback.format_exc()}"
            
            logger.error(error_msg)
            print(f"\n{'!'*80}\nEMS ERROR LOGGED:\n{error_msg}\n{'!'*80}\n")
            
            # Handle cases where EMS.run() returns incomplete or malformed data
            # Return empty arrays with appropriate shapes for all 15 expected values + wind_t, solar_t
            life_intervals = self.life_intervals
            life_h = self.life_h
            
            P_HPP_SM_t_opt = np.zeros(life_intervals)
            SM_price_cleared = np.zeros(life_h)
            BM_dw_price_cleared = np.zeros(life_h)
            BM_up_price_cleared = np.zeros(life_h)
            P_HPP_RT_ts = np.zeros(life_intervals)
            P_HPP_RT_refs = np.zeros(life_intervals)
            P_HPP_UP_bid_ts = np.zeros(life_intervals)
            P_HPP_DW_bid_ts = np.zeros(life_intervals)
            s_UP_t = np.zeros(life_intervals)
            s_DW_t = np.zeros(life_intervals)
            residual_imbalance = np.zeros(life_intervals)
            RES_RT_cur_ts = np.zeros(life_intervals)
            P_curtailment_ts = np.zeros(life_intervals)
            P_dis_RT_ts = np.zeros(life_intervals)
            P_cha_RT_ts = np.zeros(life_intervals)
            E_SOC_ts = np.zeros(life_intervals + 1)
            wind_t = np.zeros(life_intervals)
            solar_t = np.zeros(life_intervals)
        
        P_charge_discharge_ts = -P_dis_RT_ts + P_cha_RT_ts
        
        # Safely update E_SOC_ts endpoint
        try:
            if len(np.atleast_1d(E_SOC_ts)) > 1:
                E_SOC_ts[-1] = E_SOC_ts[0]
        except (IndexError, TypeError):
            pass

        # Safely expand arrays, handling potential empty/malformed data
        try:
            outputs["P_HPP_SM_t_opt"] = expand_to_lifetime(
                P_HPP_SM_t_opt,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["P_HPP_SM_t_opt"] = np.zeros(self.life_intervals)
        
        try:
            outputs["SM_price_cleared"] = expand_to_lifetime(
                SM_price_cleared, life=self.life_h, intervals_per_hour=1
            )
        except (IndexError, ValueError):
            outputs["SM_price_cleared"] = np.zeros(self.life_h)
            
        try:
            outputs["BM_dw_price_cleared"] = expand_to_lifetime(
                BM_dw_price_cleared, life=self.life_h, intervals_per_hour=1
            )
        except (IndexError, ValueError):
            outputs["BM_dw_price_cleared"] = np.zeros(self.life_h)
            
        try:
            outputs["BM_up_price_cleared"] = expand_to_lifetime(
                BM_up_price_cleared, life=self.life_h, intervals_per_hour=1
            )
        except (IndexError, ValueError):
            outputs["BM_up_price_cleared"] = np.zeros(self.life_h)
            
        try:
            outputs["P_HPP_ts"] = expand_to_lifetime(
                P_HPP_RT_ts,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["P_HPP_ts"] = np.zeros(self.life_intervals)
            
        try:
            outputs["P_HPP_RT_refs"] = expand_to_lifetime(
                P_HPP_RT_refs,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["P_HPP_RT_refs"] = np.zeros(self.life_intervals)
            
        try:
            outputs["P_HPP_UP_bid_ts"] = expand_to_lifetime(
                P_HPP_UP_bid_ts,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["P_HPP_UP_bid_ts"] = np.zeros(self.life_intervals)
            
        try:
            outputs["P_HPP_DW_bid_ts"] = expand_to_lifetime(
                P_HPP_DW_bid_ts,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["P_HPP_DW_bid_ts"] = np.zeros(self.life_intervals)
            
        try:
            outputs["s_UP_t"] = expand_to_lifetime(
                s_UP_t, life=self.life_intervals, intervals_per_hour=self.intervals_per_hour
            )
        except (IndexError, ValueError):
            outputs["s_UP_t"] = np.zeros(self.life_intervals)
            
        try:
            outputs["s_DW_t"] = expand_to_lifetime(
                s_DW_t, life=self.life_intervals, intervals_per_hour=self.intervals_per_hour
            )
        except (IndexError, ValueError):
            outputs["s_DW_t"] = np.zeros(self.life_intervals)
            
        try:
            outputs["residual_imbalance"] = expand_to_lifetime(
                residual_imbalance,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["residual_imbalance"] = np.zeros(self.life_intervals)
            
        try:
            outputs["P_curtailment_ts"] = expand_to_lifetime(
                P_curtailment_ts,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["P_curtailment_ts"] = np.zeros(self.life_intervals)
            
        try:
            outputs["P_charge_discharge_ts"] = expand_to_lifetime(
                P_charge_discharge_ts,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["P_charge_discharge_ts"] = np.zeros(self.life_intervals)
            
        try:
            outputs["E_SOC_ts"] = expand_to_lifetime(
                E_SOC_ts,
                life=self.life_intervals + 1,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["E_SOC_ts"] = np.zeros(self.life_intervals + 1)
        
        try:
            outputs["wind_t"] = expand_to_lifetime(
                wind_t,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["wind_t"] = np.zeros(self.life_intervals)
        
        try:
            outputs["solar_t"] = expand_to_lifetime(
                solar_t,
                life=self.life_intervals,
                intervals_per_hour=self.intervals_per_hour,
            )
        except (IndexError, ValueError):
            outputs["solar_t"] = np.zeros(self.life_intervals)
        
        out_keys = [
            "P_HPP_SM_t_opt",
            "SM_price_cleared",
            "BM_dw_price_cleared",
            "BM_up_price_cleared",
            "P_HPP_ts",
            "P_HPP_RT_refs",
            "P_HPP_UP_bid_ts",
            "P_HPP_DW_bid_ts",
            "s_UP_t",
            "s_DW_t",
            "residual_imbalance",
            "P_curtailment_ts",
            "P_charge_discharge_ts",
            "E_SOC_ts",
            "wind_t",
            "solar_t",
        ]
        return [outputs[k] for k in out_keys]


class ems_comp(ComponentWrapper):
    def __init__(self, **insta_inp):
        model = ems(**insta_inp)
        super().__init__(
            inputs=[
                (
                    "G_MW",
                    dict(units="MW", desc="Grid size"),
                ),
                (
                    "wind_MW",
                    dict(units="MW", desc="Wind plant nominal size"),
                ),
                (
                    "solar_MW",
                    dict(units="MW", desc="Solar plant nominal size"),
                ),
                (
                    "b_E",
                    dict(desc="Battery energy storage capacity"),
                ),
                (
                    "battery_depth_of_discharge",
                    dict(desc="battery depth of discharge", units="MW"),
                ),
                (
                    "b_P",
                    dict(desc="Battery power capacity", units="MW"),
                ),
                (
                    "wind_t_da",
                    dict(
                        desc="day ahead power time series at the hub height",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
                (
                    "wind_t_ha",
                    dict(
                        desc="hour ahead power time series at the hub height",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
                (
                    "wind_t_rt",
                    dict(
                        desc="real time power time series at the hub height",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
                (
                    "wind_t_measurement",
                    dict(
                        desc="real time power time series at the hub height",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
                (
                    "solar_t_da",
                    dict(
                        desc="day ahead pv power time series",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
                (
                    "solar_t_ha",
                    dict(
                        desc="hour ahead pv power time series",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
                (
                    "solar_t_rt",
                    dict(
                        desc="real time pv power time series",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
                (
                    "solar_t_measurement",
                    dict(
                        desc="real time pv power time series",
                        units="MW",
                        shape=[model.N_time],
                    ),
                ),
            ],
            # ----------------------------------------------------------------------------------------------------------
            outputs=[
                (
                    "P_HPP_SM_t_opt",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "SM_price_cleared",
                    dict(
                        desc="",
                        shape=[model.life_h],
                    ),
                ),
                (
                    "BM_dw_price_cleared",
                    dict(
                        desc="",
                        shape=[model.life_h],
                    ),
                ),
                (
                    "BM_up_price_cleared",
                    dict(
                        desc="",
                        shape=[model.life_h],
                    ),
                ),
                (
                    "P_HPP_ts",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "P_HPP_RT_refs",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "P_HPP_UP_bid_ts",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "P_HPP_DW_bid_ts",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "s_UP_t",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "s_DW_t",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "residual_imbalance",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "P_curtailment_ts",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "P_charge_discharge_ts",
                    dict(
                        desc="",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "E_SOC_ts",
                    dict(
                        desc="",
                        shape=[model.life_intervals + 1],
                    ),
                ),
                (
                    "wind_t",
                    dict(
                        desc="Wind power generation time series [MW]",
                        units="MW",
                        shape=[model.life_intervals],
                    ),
                ),
                (
                    "solar_t",
                    dict(
                        desc="Solar power generation time series [MW]",
                        units="MW",
                        shape=[model.life_intervals],
                    ),
                ),
            ],
            function=model.compute,
            partial_options=[{"dependent": False, "val": 0}],
        )


if __name__ == "__main__":
    from hydesign.examples import examples_filepath

    dic = {
        "wind_fn": examples_filepath + "HiFiEMS_inputs/Power/Winddata2021_15min.csv",
        "solar_fn": examples_filepath + "HiFiEMS_inputs/Power/Solardata2021_15min.csv",
        "market_fn": examples_filepath + "HiFiEMS_inputs/Market/Market2021.csv",
    }

    Wind_data = pd.read_csv(dic["wind_fn"])
    Solar_data = pd.read_csv(dic["solar_fn"])
    Market_data = pd.read_csv(dic["market_fn"])

    parameter_dict = {
        # hpp parameters
        "hpp_grid_connection": 100,  # in MW
        # hpp wind parameters
        "wind_capacity": 120,  # in MW
        # hpp solar parameters
        "solar_capacity": 10,  # in MW
        # hpp battery parameters
        "battery_energy_capacity": 120,  # in MWh
        "battery_power_capacity": 40,  # in MW
        "battery_minimum_SoC": 0.1,
        "battery_maximum_SoC": 0.9,
        "battery_initial_SoC": 0.1,
        "battery_hour_discharge_efficiency": 0.985,  #
        "battery_hour_charge_efficiency": 0.975,
        "battery_self_discharge_efficiency": 0,
        # hpp battery degradation parameters
        "battery_initial_degradation": 0,
        "battery_marginal_degradation_cost": 142000,  # in /MWh
        "battery_capital_cost": 142000,  # in /MWh
        "degradation_in_optimization": 0,  # 1:yes 0:no
        # bid parameters
        "max_up_bid": 50,
        "max_dw_bid": 50,
        "min_up_bid": 5,
        "min_dw_bid": 5,
        # interval parameters: note that DI must <= SI
        "dispatch_interval": 1 / 4,
        "settlement_interval": 1 / 4,
        "imbalance_fee": 0.13,  # DK: 0.13 Euro/MWh, other Nordic countries: , others: 0.001
        "battery_initial_degradation": 0,  # hpp battery degradation parameters
        "degradation_in_optimization": 0,
    }

    simulation_dict = {
        "wind_as_component": 1,
        "solar_as_component": 1,  # The code does not support for solar power plant
        "battery_as_component": 1,
        "start_date": "1/1/21",
        "number_of_run_day": 50,  #
        "out_dir": "./test/",
        "DA_wind": "DA",  # DA, Measurement
        "HA_wind": "HA",  # HA, Measurement
        "FMA_wind": "RT",  # 5min_ahead, Measurement
        "DA_solar": "DA",
        "HA_solar": "HA",
        "FMA_solar": "RT",
        "SP": "SM_forecast",  # SM_forecast;SM_cleared
        "RP": "reg_forecast",  # reg_cleared;reg_forecast_pre
        "BP": 1,  # 1:forecast value 2: perfect value
        # Data
        "wind_df": Wind_data,
        "solar_df": Solar_data,
        "market_df": Market_data,
    }

    out_keys = [
        "P_HPP_SM_t_opt",
        "SM_price_cleared",
        "BM_dw_price_cleared",
        "BM_up_price_cleared",
        "P_HPP_ts",
        "P_HPP_RT_refs",
        "P_HPP_UP_bid_ts",
        "P_HPP_DW_bid_ts",
        "s_UP_t",
        "s_DW_t",
        "residual_imbalance",
        "P_curtailment_ts",
        "P_charge_discharge_ts",
        "E_SOC_ts",
    ]

    # Test code disabled - use ems_comp class wrapper instead
    # res = ems_cplex(parameter_dict, simulation_dict)
    # lst = []
    # for k, r in zip(out_keys, res):
    #     lst.append({"key": k, "sum": r.sum(), "mean": r.mean(), "size": r.size})
    # df = pd.DataFrame(lst)
    #
    # outputs = {}
    # life_y = 25
    # intervals_per_hour = 4
    # life_h = life_y * 365 * 24
    # life_intervals = life_h * intervals_per_hour
    # outputs["P_HPP_SM_t_opt"] = expand_to_lifetime(
    #     res[out_keys.index("P_HPP_SM_t_opt")], life=life_intervals
    # )
    # outputs["SM_price_cleared"] = expand_to_lifetime(
    #     res[out_keys.index("SM_price_cleared")], life=life_h
    # )
    # outputs["BM_dw_price_cleared"] = expand_to_lifetime(
    #     res[out_keys.index("BM_dw_price_cleared")], life=life_h
    # )
    # outputs["BM_up_price_cleared"] = expand_to_lifetime(
    #     res[out_keys.index("BM_up_price_cleared")], life=life_h
    # )
    # outputs["P_HPP_RT_refs"] = expand_to_lifetime(
    #     res[out_keys.index("P_HPP_RT_refs")], life=life_intervals
    # )
    # outputs["P_HPP_UP_bid_ts"] = expand_to_lifetime(
    #     res[out_keys.index("P_HPP_UP_bid_ts")], life=life_intervals
    # )
    # outputs["P_HPP_DW_bid_ts"] = expand_to_lifetime(
    #     res[out_keys.index("P_HPP_DW_bid_ts")], life=life_intervals
    # )
    # outputs["s_UP_t"] = expand_to_lifetime(
    #     res[out_keys.index("s_UP_t")], life=life_intervals
    # )
    # outputs["s_DW_t"] = expand_to_lifetime(
    #     res[out_keys.index("s_DW_t")], life=life_intervals
    # )
    # outputs["residual_imbalance"] = expand_to_lifetime(
    #     res[out_keys.index("residual_imbalance")], life=life_intervals
    # )
    # outputs["P_HPP_ts"] = expand_to_lifetime(
    #     res[out_keys.index("P_HPP_ts")], life=life_intervals
    # )
    # outputs["P_curtailment_ts"] = expand_to_lifetime(
    #     res[out_keys.index("P_curtailment_ts")], life=life_intervals
    # )
    # outputs["P_charge_discharge_ts"] = expand_to_lifetime(
    #     res[out_keys.index("P_charge_discharge_ts")], life=life_intervals
    # )
    # outputs["E_SOC_ts"] = expand_to_lifetime(
    #     res[out_keys.index("E_SOC_ts")], life=life_intervals + 1
    # )
    #
    # for k, v in outputs.items():
    #     print(k, np.shape(v))
    #
    # from hydesign.HiFiEMS.utils import Revenue_calculation
    #
    # SM_revenue, _, _, BM_revenue, _ = Revenue_calculation(
    #     parameter_dict,
    #     outputs["P_HPP_SM_t_opt"],
    #     outputs["P_HPP_ts"],
    #     outputs["P_HPP_RT_refs"],
    #     outputs["SM_price_cleared"],
    #     outputs["BM_dw_price_cleared"],
    #     outputs["BM_up_price_cleared"],
    #     outputs["P_HPP_UP_bid_ts"],
    #     outputs["P_HPP_DW_bid_ts"],
    #     outputs["s_UP_t"],
    #     outputs["s_DW_t"],
    #     BI=1,
    # )
    # total_revenue = SM_revenue + BM_revenue
    # print(total_revenue.sum() / 10**6)
